
/**
 * The constructor for the chat object.
 *
 * @constructor
 * @param {int} msgId The msgId generated by the database.
 * @param {string} msg The chat's message.
 */
function Chat(msgId, msg) {
  this.msgId = msgId;
  this.msg = msg;
}

Chat.prototype.toString = function() {
	return "The chat message's ID is: " + this.msgId + " and message itself is: " + this.msg; 
}

module.exports = Chat;
