
/**
 * The constructor for the child object.
 *
 * @constructor
 * @param {int} studentId The studentId generated by the database.
 * @param {string} firstName The first name of the child.
 * @param {string} lastName The last name of the child.
 */
function Child(studentId, firstName, lastName) {
  this.studentId = studentId;
  this.firstName = firstName;
  this.lastName = lastName;
}

Child.prototype.toString = function() {
	return "The child's name is: " + this.firstName + " " + this.lastName + " and their student ID is: " + this.studentId; 
}

module.exports = Child;
