
/**
 * The constructor for the course object.
 *
 * @constructor
 * @param {string} courseId The courseId generated by the database.
 * @param {string} courseName The name of the course.
 */
function Course(courseId, courseName) {
  this.courseId = courseId;
  this.courseName = courseName;
}

Course.prototype.toString = function() {
	return "The course's ID is: " + this.courseId + " " + " and course's name is: " + this.courseName; 
}

module.exports = Course;
